spring:
  application:
    name: bill
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgresql:5432/bill}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      # todo add init_data db migration and change it to create-drop
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
    show-sql: true

server.port: 8080

spring.messages:
  basename: messages
  encoding: UTF-8
  fallback-to-system-locale: true
  use-code-as-default-message: false
